#!/bin/bash
# =============================================================================
# AlgeriaTrade.dz API Developer Portal - Initial Setup Script
# Creates database schema, seeds data, configures SSL & email
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEPLOY_DIR="$PROJECT_ROOT/deploy/api-portal"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[SETUP]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*"; }

# =============================================================================
# Generate Secure Secrets
# =============================================================================
generate_secrets() {
    log_info "Generating secure secrets..."
    
    local env_file="$DEPLOY_DIR/.env.production"
    
    # Create .env file if it doesn't exist
    if [ ! -f "$env_file" ]; then
        cat > "$env_file" << 'EOF'
# AlgeriaTrade.dz API Developer Portal - Production Environment
# Generated by setup script on $(date)
EOF
    fi
    
    # Generate JWT Secret (256 bits = 32 bytes)
    if ! grep -q "JWT_SECRET=" "$env_file" 2>/dev/null; then
        local jwt_secret=$(openssl rand -base64 32 | tr -d '\n')
        echo "JWT_SECRET=${jwt_secret}" >> "$env_file"
        log_success "Generated JWT_SECRET"
    fi
    
    # Generate JWT Refresh Secret (different from access token secret)
    if ! grep -q "JWT_REFRESH_SECRET=" "$env_file" 2>/dev/null; then
        local refresh_secret=$(openssl rand -base64 32 | tr -d '\n')
        echo "JWT_REFRESH_SECRET=${refresh_secret}" >> "$env_file"
        log_success "Generated JWT_REFRESH_SECRET"
    fi
    
    # Generate Encryption Key (AES-256-GCM requires 256-bit key)
    if ! grep -q "ENCRYPTION_KEY=" "$env_file" 2>/dev/null; then
        local enc_key=$(openssl rand -hex 32)
        echo "ENCRYPTION_KEY=${enc_key}" >> "$env_file"
        log_success "Generated ENCRYPTION_KEY"
    fi
    
    # Generate Webhook Secret
    if ! grep -q "WEBHOOK_SECRET=" "$env_file" 2>/dev/null; then
        local webhook_secret=$(openssl rand -hex 24)
        echo "WEBHOOK_SECRET=${webhook_secret}" >> "$env_file"
        log_success "Generated WEBHOOK_SECRET"
    fi
    
    # Generate PostgreSQL Password
    if ! grep -q "POSTGRES_PASSWORD=" "$env_file" 2>/dev/null; then
        local pg_password=$(openssl rand -base64 16 | tr -d '=' | cut -c1-20)
        echo "POSTGRES_PASSWORD=${pg_password}" >> "$env_file"
        log_success "Generated POSTGRES_PASSWORD"
    fi
    
    # Generate Redis Password
    if ! grep -q "REDIS_PASSWORD=" "$env_file" 2>/dev/null; then
        local redis_password=$(openssl rand -base64 16 | tr -d '=' | cut -c1-20)
        echo "REDIS_PASSWORD=${redis_password}" >> "$env_file"
        log_success "Generated REDIS_PASSWORD"
    fi
    
    # Generate Admin Password
    if ! grep -q "ADMIN_INITIAL_PASSWORD=" "$env_file" 2>/dev/null; then
        local admin_pass=$(openssl rand -base64 12 | tr -d '=' | cut -c1-16)
        echo "ADMIN_INITIAL_PASSWORD=${admin_pass}" >> "$env_file"
        log_success "Generated ADMIN_INITIAL_PASSWORD: ${admin_pass}"
        log_warn "Save this admin password securely!"
    fi
    
    log_success "Secrets generation completed."
}

# =============================================================================
# Create Database Schema
# =============================================================================
create_database_schema() {
    log_info "Creating database schema..."
    
    cd "$PROJECT_ROOT"
    
    # Ensure Prisma is installed
    if [ ! -d "node_modules/@prisma/client" ]; then
        npm install @prisma/client prisma --save-dev
    fi
    
    # Generate Prisma client
    npx prisma generate
    
    # Create initial migration
    npx prisma migrate dev --name init --create-only || true
    
    # Push schema to database (for production, use migrate deploy)
    npx prisma db push || {
        log_error "Failed to create database schema!"
        exit 1
    }
    
    log_success "Database schema created."
}

# =============================================================================
# Seed Initial Data
# =============================================================================
seed_initial_data() {
    log_info "Seeding initial data..."
    
    cd "$PROJECT_ROOT"
    
    # Create seed script if it doesn't exist
    local seed_script="$DEPLOY_DIR/init-scripts/seed-data.sql"
    
    mkdir -p "$DEPLOY_DIR/init-scripts"
    
    cat > "$seed_script" << 'SEED_SQL'
-- =============================================================================
-- AlgeriaTrade.dz API Developer Portal - Initial Seed Data
-- =============================================================================

-- Developer Plans/Tiers
INSERT INTO "DeveloperPlan" ("id", "name", "slug", "description", "priceMonthlyDzd", "priceYearlyDzd", "requestsPerMonth", "rateLimitPerMinute", "maxApiKeys", "webhooksEnabled", "customBranding", "supportLevel", "slaGuarantee", "features", "createdAt", "updatedAt") VALUES
('free-plan', 'Free', 'free', 'Plan gratuit pour les développeurs débutants et les projets personnels', 0, 0, 1000, 10, 1, false, false, 'community', NULL, ARRAY['public_apis', 'basic_docs', 'community_support'], NOW(), NOW()),
('pro-plan', 'Pro', 'pro', 'Plan professionnel pour les entreprises en croissance', 9990, 99900, 100000, 100, 5, true, false, 'email', '99.5%', ARRAY['public_apis', 'all_tiers', 'priority_support', 'email_support', 'webhooks', 'analytics'], NOW(), NOW()),
('enterprise-plan', 'Enterprise', 'enterprise', 'Solution sur mesure pour les grandes entreprises', 99990, 999900, NULL, 1000, NULL, true, true, 'dedicated_csm', '99.9%', ARRAY['public_apis', 'all_tiers', 'beta_access', 'dedicated_support', 'unlimited_webhooks', 'custom_branding', 'analytics', 'sla_guarantee', 'priority_routing'], NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- API Categories
INSERT INTO "ApiCategory" ("id", "name", "slug", "description", "icon", "sortOrder", "isActive", "createdAt", "updatedAt") VALUES
('cat-products', 'Produits', 'products', 'Accès au catalogue de produits algériens', 'package', 1, true, NOW(), NOW()),
('cat-companies', 'Entreprises', 'companies', 'Base de données des entreprises algériennes', 'building', 2, true, NOW(), NOW()),
('cat-commerce', 'Commerce', 'commerce', 'APIs de commerce électronique B2B', 'shopping-cart', 3, true, NOW(), NOW()),
('cat-logistics', 'Logistique', 'logistique', 'Suivi d''expédition et transport', 'truck', 4, true, NOW(), NOW()),
('cat-payments', 'Paiements', 'payments', 'Intégration paiement (CCP, BaridiMob)', 'credit-card', 5, true, NOW(), NOW()),
('cat-auth', 'Authentification', 'auth', 'Authentification et gestion des utilisateurs', 'shield', 6, true, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Rate Limit Tiers
INSERT INTO "RateLimitTier" ("id", "name", "requestsPerMinute", "requestsPerHour", "requestsPerDay", "concurrentConnections", "createdAt", "updatedAt") VALUES
('tier-free', 'Gratuit', 10, 500, 1000, 2, NOW(), NOW()),
('tier-pro', 'Pro', 100, 5000, 10000, 10, NOW(), NOW()),
('tier-enterprise', 'Enterprise', 1000, 50000, NULL, 50, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Documentation Pages
INSERT INTO "DocumentationPage" ("id", "title", "slug", "content", "category", "orderIndex", "isPublished", "viewCount", "createdAt", "updatedAt") VALUES
('doc-getting-started', 'Commencer', 'getting-started', '# Guide de Démarrage Rapide\n\nBienvenue sur l''API AlgeriaTrade.dz...', 'guides', 1, true, 0, NOW(), NOW()),
('doc-authentication', 'Authentification', 'authentication', '# Authentification\n\nToutes les requêtes API nécessitent une clé API valide...', 'reference', 2, true, 0, NOW(), NOW()),
('doc-rate-limits', 'Limites de Taux', 'rate-limits', '# Limites de Taux d''Appel\n\nChaque plan a ses propres limites...', 'reference', 3, true, 0, NOW(), NOW()),
('doc-error-codes', 'Codes d''Erreur', 'error-codes', '# Codes d''Erreur\n\nRéférence complète des codes d''erreur...', 'reference', 4, true, 0, NOW(), NOW()),
('doc-webhooks', 'Webhooks', 'webhooks', '# Configuration des Webhooks\n\nLes webhooks permettent de recevoir des notifications...', 'guides', 5, true, 0, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Default Settings
INSERT INTO "PortalSetting" ("key", "value", "description", "isPublic", "updatedAt") VALUES
('maintenance_mode', 'false', 'Mode maintenance du portail', true, NOW()),
('api_version', 'v1.0.0', 'Version actuelle de l''API', true, NOW()),
('max_request_size', '10485760', 'Taille maximale des requêtes en octets', true, NOW()),
('cors_origins', '["https://portal.algeriatrade.dz","https://*.algeriatrade.dz"]', 'Origines CORS autorisées', true, NOW()),
('default_rate_limit', '100', 'Limite de taux par défaut par minute', true, NOW()),
('session_timeout', '3600', 'Délai d''expiration de session en secondes', false, NOW()),
('email_verification_required', 'true', 'Nécessite la vérification email pour les comptes développeur', true, NOW()),
('api_key_rotation_days', '90', 'Jours avant rotation recommandée des clés API', false, NOW())
ON CONFLICT (key) DO NOTHING;

-- Create default admin user (password will be set separately)
INSERT INTO "DeveloperAccount" ("id", "email", "displayName", "companyName", "role", "planId", "status", "emailVerified", "mfaEnabled", "lastLoginAt", "createdAt", "updatedAt")
VALUES ('admin-default', 'admin@algeriatrade.dz', 'Administrateur', 'AlgeriaTrade.dz', 'admin', 'enterprise-plan', 'active', true, false, NOW(), NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
SEED_LOG
    
    # Execute seed SQL via Docker
    if docker-compose -f "$DEPLOY_DIR/docker-compose.api-portal.yml" ps postgres 2>/dev/null | grep -q "Up"; then
        docker-compose -f "$DEPLOY_DIR/docker-compose.api-portal.yml" exec -T postgres \
            psql -U apiportal -d algeriatrade_portal < "$seed_script" && \
            log_success "Initial data seeded successfully."
    else
        log_warn "PostgreSQL not running. Seed data will be applied during deployment."
    fi
}

# =============================================================================
# Configure SSL Certificates
# =============================================================================
setup_ssl_certificates() {
    log_info "Setting up SSL certificates..."
    
    local ssl_dir="$DEPLOY_DIR/nginx/ssl"
    mkdir -p "$ssl_dir"
    
    # Check if Let's Encrypt certificates should be used
    if [ "${USE_LETS_ENCRYPT:-true}" = "true" ]; then
        log_info "Configuring Let's Encrypt certificates..."
        
        # Create certbot directory for ACME challenges
        mkdir -p "$DEPLOY_DIR/certbot/www"
        
        # Check if certbot is available
        if command -v certbot &> /dev/null; then
            # Request certificate (requires DNS to be configured first)
            local domains=("portal.algeriatrade.dz" "api.algeriatrade.dz")
            
            for domain in "${domains[@]}"; do
                certbot certonly \
                    --webroot \
                    -w "$DEPLOY_DIR/certbot/www" \
                    -d "$domain" \
                    --non-interactive \
                    --agree-tos \
                    --email "admin@algeriatrade.dz" || \
                    log_warn "Could not obtain certificate for $domain. Using self-signed."
            done
            
            # Copy certificates to nginx ssl directory
            if [ -f "/etc/letsencrypt/live/portal.algeriatrade.dz/fullchain.pem" ]; then
                cp /etc/letsencrypt/live/portal.algeriatrade.dz/fullchain.pem "$ssl_dir/"
                cp /etc/letsencrypt/live/portal.algeriatrade.dz/privkey.pem "$ssl_dir/"
                cp /etc/letsencrypt/live/portal.algeriatrade.dz/chain.pem "$ssl_dir/"
                log_success "Let's Encrypt certificates installed."
            fi
        else
            log_warn "Certbot not found. Generating self-signed certificates..."
            generate_self_signed_certs
        fi
    else
        generate_self_signed_certs
    fi
}

generate_self_signed_certs() {
    local ssl_dir="$DEPLOY_DIR/nginx/ssl"
    
    # Generate self-signed certificate for development/testing
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$ssl_dir/privkey.pem" \
        -out "$ssl_dir/fullchain.pem" \
        -subj "/C=DZ/O=AlgeriaTrade.dz/CN=*.algeriatrade.dz" \
        -addext "subjectAltName=DNS:*.algeriatrade.dz,DNS:localhost"
    
    # Create chain file (same as fullchain for self-signed)
    cp "$ssl_dir/fullchain.pem" "$ssl_dir/chain.pem"
    
    log_warn "Self-signed certificates generated. Use only for testing!"
}

# =============================================================================
# Configure Email Service
# =============================================================================
configure_email_service() {
    log_info "Configuring email service..."
    
    local env_file="$DEPLOY_DIR/.env.production"
    
    # Prompt for SMTP configuration if not already set
    if ! grep -q "SMTP_HOST=" "$env_file" 2>/dev/null; then
        echo ""
        log_info "Please enter your SMTP configuration:"
        
        read -rp "SMTP Host [smtp.mailgun.org]: " smtp_host
        smtp_host="${smtp_host:-smtp.mailgun.org}"
        
        read -rp "SMTP Port [587]: " smtp_port
        smtp_port="${smtp_port:-587}"
        
        read -rp "SMTP User [postmaster@algeriatrade.dz]: " smtp_user
        smtp_user="${smtp_user:-postmaster@algeriatrade.dz}"
        
        read -rsp "SMTP Password: " smtp_pass
        echo ""
        
        cat >> "$env_file" << EOF
SMTP_HOST=${smtp_host}
SMTP_PORT=${smtp_port}
SMTP_USER=${smtp_user}
SMTP_PASS=${smtp_pass}
EMAIL_FROM=noreply@algeriatrade.dz
EOF
        
        log_success "Email configuration saved."
    fi
    
    # Test email connection
    if command -v python3 &> /dev/null; then
        log_info "Testing SMTP connection..."
        source "$env_file"
        python3 << PYTEST
import smtplib
try:
    server = smtplib.SMTP("${SMTP_HOST}", ${SMTP_PORT})
    server.starttls()
    server.login("${SMTP_USER}", "${SMTP_PASS}")
    server.quit()
    print("Email connection test successful!")
except Exception as e:
    print(f"Email test failed: {e}")
PYTEST
    fi
}

# =============================================================================
# Setup Monitoring Stack
# =============================================================================
setup_monitoring() {
    log_info "Setting up monitoring stack..."
    
    # Create Grafana provisioning directories
    mkdir -p "$DEPLOY_DIR/monitoring/grafana-provisioning/datasources"
    mkdir -p "$DEPLOY_DIR/monitoring/grafana-provisioning/dashboards"
    
    # Prometheus datasource configuration
    cat > "$DEPLOY_DIR/monitoring/grafana-provisioning/datasources/prometheus.yml" << 'EOF'
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
EOF
    
    # Dashboard provider configuration
    cat > "$DEPLOY_DIR/monitoring/grafana-provisioning/dashboards/provider.yml" << 'EOF'
apiVersion: 1
providers:
  - name: 'AlgeriaTrade API Portal'
    orgId: 1
    folder: ''
    type: file
    disableDeletion: true
    editable: true
    options:
      path: /var/lib/grafana/dashboards
EOF
    
    # Prometheus main configuration
    cat > "$DEPLOY_DIR/monitoring/prometheus.yml" << 'PROMETHEUS'
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'algeriatrade-api-portal'

scrape_configs:
  # API Portal application metrics
  - job_name: 'api-portal'
    scrape_interval: 15s
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/api/metrics'
    relabel_configs:
      - target_label: environment
        replacement: production

  # Node exporter for infrastructure metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
PROMETHEUS
    
    log_success "Monitoring configuration created."
}

# =============================================================================
# Create Required Directories
# =============================================================================
create_directories() {
    log_info "Creating required directories..."
    
    local dirs=(
        "$DEPLOY_DIR/backups"
        "$DEPLOY_DIR/logs"
        "$DEPLOY_DIR/init-scripts"
        "$DEPLOY_DIR/nginx/snippets"
        "$DEPLOY_DIR/static"
        "$DEPLOY_DIR/monitoring"
        "$PROJECT_ROOT/data/uploads"
        "$PROJECT_ROOT/data/temp"
    )
    
    for dir in "${dirs[@]}"; do
        mkdir -p "$dir"
    done
    
    # Set proper permissions
    chmod 750 "$DEPLOY_DIR/backups"
    chmod 750 "$DEPLOY_DIR/nginx/ssl"
    
    log_success "Directories created."
}

# =============================================================================
# Display Summary
# =============================================================================
display_summary() {
    echo ""
    echo "============================================================"
    echo "  ALGERIATRADE.DZ API PORTAL - SETUP COMPLETE"
    echo "============================================================"
    echo ""
    echo "  Next steps:"
    echo ""
    echo "  1. Review and update $DEPLOY_DIR/.env.production"
    echo "     with your actual values"
    echo ""
    echo "  2. Configure DNS records:"
    echo "     portal.algeriatrace.dz -> your_server_ip"
    echo "     api.algeriatrade.dz -> your_server_ip"
    echo ""
    echo "  3. Run deployment:"
    echo "     ./deploy/api-portal/scripts/deploy.sh"
    echo ""
    echo "  4. Access the portal at https://portal.algeriatrade.dz"
    echo ""
    echo "  Admin credentials:"
    echo "     Email: admin@algeriatrade.dz"
    echo "     Password: See ADMIN_INITIAL_PASSWORD in .env.production"
    echo ""
    echo "============================================================"
}

# =============================================================================
# Main Setup Flow
# =============================================================================
main() {
    echo ""
    echo "============================================================"
    echo "  AlgeriaTrade.dz API Developer Portal - Initial Setup"
    echo "  Date: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "============================================================"
    echo ""
    
    create_directories
    generate_secrets
    create_database_schema
    seed_initial_data
    setup_ssl_certificates
    configure_email_service
    setup_monitoring
    
    display_summary
}

main "$@"
